apiVersion: v1
kind: Service
metadata:
  name: release-demo-service-canary
  labels:
    app: release-demo-service
    component: api
    track: canary
spec:
  type: ClusterIP
  selector:
    app: release-demo-service
    component: api
    track: canary
  ports:
    - name: http
      port: 80
      targetPort: 8000
