#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  bash scripts/release-record.sh <environment> <version> <commit_sha> <status>

Example:
  bash scripts/release-record.sh production v1.1.0 abcdef1 success
USAGE
}

log() {
  printf '[release-record] %s\n' "$*"
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -ne 4 ]]; then
  usage
  exit 1
fi

ENVIRONMENT="$1"
VERSION="$2"
COMMIT_SHA="$3"
STATUS="$4"

case "${ENVIRONMENT}" in
  dev|staging|production) ;;
  *)
    echo "ERROR: environment must be one of: dev, staging, production." >&2
    usage
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
RECORD_DIR="${ROOT_DIR}/release-records"
DATE="$(date -u +"%Y-%m-%d")"
BUILD_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
IMAGE_NAME="${IMAGE_NAME:-ghcr.io/shaohan-he/release-demo-service}"
OPERATOR="${GITHUB_ACTOR:-${USER:-unknown}}"
WORKFLOW="${GITHUB_WORKFLOW:-local-script}"
PREVIOUS_VERSION="${PREVIOUS_VERSION:-unknown}"
FILE="${RECORD_DIR}/${DATE}-${VERSION}-${ENVIRONMENT}.md"

mkdir -p "${RECORD_DIR}"

cat >"${FILE}" <<EOF
# Release Record: ${VERSION} / ${ENVIRONMENT}

> Status: ${STATUS}

| Field | Value |
| --- | --- |
| Environment | ${ENVIRONMENT} |
| Version | ${VERSION} |
| Image | ${IMAGE_NAME}:${VERSION} |
| Commit SHA | ${COMMIT_SHA} |
| Build Time | ${BUILD_TIME} |
| Operator | ${OPERATOR} |
| Workflow | ${WORKFLOW} |
| Unit Test | ${UNIT_TEST_RESULT:-unknown} |
| Docker Build | ${DOCKER_BUILD_RESULT:-unknown} |
| Trivy Scan | ${TRIVY_SCAN_RESULT:-unknown} |
| Kustomize Render | ${KUSTOMIZE_RENDER_RESULT:-unknown} |
| Kubernetes Rollout | ${KUBERNETES_ROLLOUT_RESULT:-unknown} |
| Smoke Test | ${SMOKE_TEST_RESULT:-unknown} |
| Previous Version | ${PREVIOUS_VERSION} |

## Rollback Command

\`\`\`bash
bash scripts/rollback.sh ${ENVIRONMENT} ${PREVIOUS_VERSION}
\`\`\`

## Notes

- This record is generated by the release pipeline practice project.
- For real production usage, attach approval evidence, incident links, metrics snapshots, and audit logs.
EOF

log "Release record generated: ${FILE}"
