apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-staging
resources:
  - ../../base
images:
  - name: ghcr.io/shaohan-he/release-demo-service
    newTag: staging-latest
patches:
  - path: patch.yaml
